fix 18730 of 18922 java.lang.NullPointerException crashes
2020-06-02 navigatorType was null because uninitialized, causing 18730 of 18922 crashes with message:
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference

crashed loadTutorGraph
switch(navigatorType) { // 2020-06-02 was null because uninitialized, causing > 18,000 crashes
            case TCONST.SIMPLENAV:  // 2020-06-02 JM make this the default value because the other value isn't used